services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true

  Virtua\ShopwareAppLoggerBundle\:
    resource: '../../'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Exception/'